[GH-748] Upgraded IDNA library and adjusted NameUtil module
aeternity/elixir-node pull request #782
Opened 2018-11-13 12:27 UTC by DanielaIvanova

resolves #748

2018-11-13 19:14 UTC, thepiwo requested changes

2018-11-14 08:30 UTC, DanielaIvanova commented on apps/aecore/lib/aecore/naming/name_util.ex
> +        {:ok, normalize_name(name)}
`Epoch` does the same. You can [check](https://github.com/aeternity/epoch/blob/v0.25.0/apps/aens/src/aens_utils.erl#L38)

2018-11-14 09:42 UTC, DanielaIvanova commented on apps/aecore/lib/aecore/naming/name_util.ex
> +      List.to_string(name_unicode_list)
You are right! I will fix it.

2018-11-14 15:27 UTC, thepiwo approved these changes
seems good

2018-11-15 08:44 UTC, Artur64 approved these changes

2018-11-15 08:46 UTC, d-velev commented on apps/aecore/lib/aecore/naming/name_util.ex
> +        {:ok, normalize_name(name)}
Could you rename the function to validate_name instead so it's not confusing?

2018-11-15 12:55 UTC, cytadela8 approved these changes

2018-11-16 03:44 UTC, merged