[GH-738] Added identifiers to both Name and NameCommitment structures
aeternity/elixir-node pull request #785
Opened 2018-11-13 14:43 UTC by Artur64

resolves #738 . Blocked until #782  and #784 is merged. Also, its worth mentioning that the code should be tested before merging this PR.

2018-11-13 19:17 UTC, thepiwo submitted a review, later dismissed

2018-11-14 08:42 UTC, d-velev submitted a review, later dismissed

2018-11-14 09:49 UTC, DanielaIvanova submitted a review, later dismissed

2018-11-15 13:03 UTC, cytadela8 requested changes

2018-11-15 13:03 UTC, cytadela8 commented on apps/aecore/lib/aecore/naming/name.ex
> +    {:ok, decoded_owner} = Identifier.decode_from_binary(owner)
You should:
- check for errors here
- check the type of identifier you decode. There is a a nice function to do that: `Identifier.decode_from_binary_to_value`

2018-11-15 13:03 UTC, cytadela8 commented on apps/aecore/lib/aecore/naming/name_commitment.ex
> +    {:ok, decoded_owner} = Identifier.decode_from_binary(encoded_owner)
Above applies also here.

2018-11-15 14:58 UTC, cytadela8 approved these changes

2018-11-16 03:45 UTC, thepiwo approved these changes

2018-11-16 03:45 UTC, merged